In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# Define Sequential Model with 3 layers
model = keras.Sequential([
    layers.Dense(2,activation = "relu", name = "layer1"),
    layers.Dense(3,activation = "relu", name = "Layer 2"),
    layers.Dense(4, name = "layer3")
])

# Call Model on a test input
x = tf.ones((3,3))
y = model(x)

In [3]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.47311515,  0.19485539, -0.32168615, -0.24697742],
       [-0.47311515,  0.19485539, -0.32168615, -0.24697742],
       [-0.47311515,  0.19485539, -0.32168615, -0.24697742]],
      dtype=float32)>

In [14]:
# Creeate 3 Layers
layer1 = layers.Dense(2, activation= 'relu', name = "layer1")
layer2 = layers.Dense(3, activation = "relu", name = "layer2")
layer3 = layers.Dense(4, name = "layer3")

## Call Layer on a test input
x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))

In [6]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [12]:
x = tf.ones(3,3)
x.numpy()

array([1, 1, 1])

In [15]:
layer1(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.        , 0.90239525],
       [0.        , 0.90239525],
       [0.        , 0.90239525]], dtype=float32)>

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (3, 2)                    8         
                                                                 
 Layer 2 (Dense)             multiple                  9         
                                                                 
 layer3 (Dense)              multiple                  16        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [21]:
model = keras.Sequential()
model.add(keras.Input(shape=(5,)))
model.add(layers.Dense(20,activation = "relu"))

In [22]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 20)                120       
                                                                 
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________
